pipeline {
  agent any
  stages {
  	  
  stage ('Build') {



            steps {

                withMaven(maven : 'maven_3_5_0') {

                    sh 'mvn build'

                }

            }

        }



        stage ('Testing Stage') {



            steps {

                withMaven(maven : 'maven_3_5_0') {

                    sh 'mvn test'

                }

            }

        }
  }
}